"""Initial migration

Revision ID: db3d47b677ba
Revises: 
Create Date: 2023-11-20 15:49:37.650286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3d47b677ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('date_posted', sa.DateTime(), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('poster_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('about_author', sa.Text(), nullable=True),
        sa.Column('date_added', sa.DateTime(), nullable=True),
        sa.Column('favorite_color', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('profile_pic', sa.String(length=100), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('email'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'name')
    op.drop_column('users', 'favorite_color')
    op.drop_column('users', 'date_added')
    op.drop_column('users', 'about_author')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('posts')
    # ### end Alembic commands ###
